image: Ubuntu1804
stack: "node 10"
branches:
  only:
    - master
cache: node_modules
install:
  - cd ~/yarn-cd
  - yarn install
  - cd ~/dom
  - yarn install
build: off
build_script:
  - cd ~/yarn-cd
  - yarn build
  - cd ~/dom
  - yarn build
test_script:
  - cd ~/yarn-cd
  - yarn test
  - cd ~/dom
  - yarn test
deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - mkdir ~/gh
  - mkdir ~/gh/01
  - mv ~/yarn-cd/dist/* ~/gh/01
  - mkdir ~/gh/02
  - mv ~/dom/dist/* ~/gh/02
  - npx push-dir --dir=~/gh --branch=gh-pages --force --verbose
